### ISSUE TITLE
stuck again

### ISSUE THREAD

**Issue by TaKeOVER15** [MGeurts/genealogy#10]
installed onto a vm 

getting this error 

   Illuminate\Database\QueryException

  could not find driver (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'genealogy' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

      +33 vendor frames

  34  artisan:13
      Illuminate\Foundation\Application::handleCommand()

**Comment by MGeurts** [comment]
You'll need a webserver and a database server. The error is caused because you don't have a valid MySQL server running.
How to install this project is mentioned in the **Installation** section. But you'll have to setup your servers yourself. Installing them is outside the scope of Laravel projects.

**Please stop creating Issues when they are not directly releated to the application itself.**
Thank you.
