### ISSUE TITLE
Can you process the proportion of the picture to make it the same size?

### ISSUE THREAD

**Issue by Goodahome** [MGeurts/genealogy#19]
![image](https://github.com/user-attachments/assets/b8640169-db88-49a0-9976-f51395797104)

**Comment by MGeurts** [comment]
The picture uploads are handled in [https://github.com/MGeurts/genealogy/blob/main/app/PersonPhotos.php](https://github.com/MGeurts/genealogy/blob/main/app/PersonPhotos.php).

The maximum width and the maximum height are defined in [https://github.com/MGeurts/genealogy/blob/main/config/app.php](https://github.com/MGeurts/genealogy/blob/main/config/app.php).

You can set the values to whatever you want.
To keep the aspect ratio correct, all images are shown in the grids with the same width. They only vary in height. Otherwise they would be distorted.
