### ISSUE TITLE
Unable to locate a class or view for component [tallstack-ui::icon.tablericons.default.circle-check]

### ISSUE THREAD

**Issue by wgmv** [MGeurts/genealogy#32]
Hi, I'm seeing this error 

`Unable to locate a class or view for component [tallstack-ui::icon.tablericons.default.circle-check]`

I'm not too familiar with livewire - is there sth missing or should I execute sth? (I'm pretty sure I didn't see this error a couple of days ago)

**Comment by MGeurts** [comment]
Thanks for reporting this issue.

The Tabler Icons were only downloaded during `composer update` and not during initial `composer install`.

This is fixed by [https://github.com/MGeurts/genealogy/commit/2bcc8d255159495c11379f92c823a0669fa4bf50](https://github.com/MGeurts/genealogy/commit/2bcc8d255159495c11379f92c823a0669fa4bf50)

In the meantime, you can just run `composer update`.
